<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQC5JaGs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQC5JaGs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQC5JaGs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQC5JaGs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQC5JaGs\App_KernelDevDebugContainer([
    'container.build_hash' => 'QC5JaGs',
    'container.build_id' => '984088eb',
    'container.build_time' => 1646296988,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQC5JaGs');
